owner: compliward
repo: status
userAgent: Compliward
assignees:
  - compliward

sites:
  - name: Compliward App
    url: https://compliward.vercel.app
  - name: Document Extraction Worker
    url: https://compliward.vercel.app/api/internal/document-extraction-process
    expectedStatusCodes:
      - 401
  - name: Alerts Worker
    url: https://compliward.vercel.app/api/internal/alerts/run
    expectedStatusCodes:
      - 401

status-website:
  cname: status.compliward.com
  name: Compliward Status
  logoUrl: https://compliward.vercel.app/favicon.ico
